"use client";

import { useState, useEffect } from "react";
import { useSession } from "next-auth/react";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import { Loader2, MoreHorizontal, Pen, Trash, Eye } from "lucide-react";
import { toast } from "sonner";
import { Layout } from "@/components/Layout";
import api from "@/lib/api";
import { redirect } from "next/navigation";
import {
  Pagination,
  PaginationContent,
  PaginationItem,
  PaginationLink,
  PaginationNext,
  PaginationPrevious,
} from "@/components/ui/pagination";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
  DialogDescription,
} from "@/components/ui/dialog";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";

interface TaskReport {
  _id: string;
  name: string;
  fileName: string;
  generatedBy: string;
  createdAt: string;
  reportDate: string;
  sheetUrl: string;
  userId: string;
  viewType: any;
}

export default function TaskReportPage() {
  const { data: session } = useSession();
  const [reports, setReports] = useState<TaskReport[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [deletingReport, setDeletingReport] = useState<TaskReport | null>(null);
  const [isDeleteDialogOpen, setIsDeleteDialogOpen] = useState(false);
  const [currentPage, setCurrentPage] = useState(1);
  const entriesPerPage = 10;

  // Columns configuration for the table
  const columns = [
    { label: "Report No.", field: "reportNumber" },

    { label: "Generated By", field: "userName" },
    { label: "File Name", field: "fileName" },
    {
      label: "Report Date",
      field: "reportDate",
      format: (value: string) => new Date(value).toLocaleString(),
    },
    { label: "View Type", field: "viewType" },
    { label: "Actions", field: "actions" },
  ];

  useEffect(() => {
    if (session?.user.role || session?.user.role === "admin") {
      fetchReports();
    } else {
      redirect("/dashboard");
    }
  }, [session]);

  const fetchReports = async () => {
    setIsLoading(true);
    try {
      const response = await api.get("/create-report");
      setReports(response.data);
    } catch (error) {
      console.error("Error fetching data:", error);
      toast.error("Failed to fetch reports");
    } finally {
      setIsLoading(false);
    }
  };

  const handleDeleteReport = async () => {
    if (!deletingReport) return;
    try {
      const response = await fetch(`/api/create-report/${deletingReport._id}`, {
        method: "DELETE",
      });
      if (response.ok) {
        setReports((prevReports) =>
          prevReports.filter((report) => report._id !== deletingReport._id)
        );
        toast.success("Report deleted successfully");
      } else {
        const errorData = await response.json();
        toast.error(errorData.message || "Failed to delete report");
      }
    } catch (error) {
      console.error("Error deleting report:", error);
      toast.error("An error occurred while deleting the report");
    } finally {
      setIsDeleteDialogOpen(false);
      setDeletingReport(null);
    }
  };

  const indexOfLastEntry = currentPage * entriesPerPage;
  const indexOfFirstEntry = indexOfLastEntry - entriesPerPage;
  const currentEntries = reports.slice(indexOfFirstEntry, indexOfLastEntry);

  return (
    <Layout>
      <div className="container mx-auto py-10">
        <div className="flex justify-between items-center mb-6">
          <h1 className="text-3xl font-bold">Task Reports</h1>
        </div>

        {isLoading ? (
          <div className="flex justify-center items-center h-64">
            <Loader2 className="h-8 w-8 animate-spin" />
          </div>
        ) : (
          <>
            <div className="rounded-md border overflow-x-auto">
              <Table>
                <TableHeader>
                  <TableRow>
                    {columns.map((col) => (
                      <TableHead key={col.field}>{col.label}</TableHead>
                    ))}
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {currentEntries.map((report: any) => (
                    <TableRow key={report._id}>
                      {columns.map((col) => (
                        <TableCell key={col.field}>
                          {col.field === "actions" ? (
                            <DropdownMenu>
                              <DropdownMenuTrigger asChild>
                                <Button variant="ghost" className="h-8 w-8 p-0">
                                  <span className="sr-only">Open menu</span>
                                  <MoreHorizontal className="h-4 w-4" />
                                </Button>
                              </DropdownMenuTrigger>
                              <DropdownMenuContent align="end">
                                <DropdownMenuLabel>Actions</DropdownMenuLabel>
                                <DropdownMenuItem
                                  onClick={() => {
                                    window.open(report.sheetUrl, "_blank");
                                  }}
                                >
                                  <Eye className="mr-2 h-4 w-4" />
                                  View Report
                                </DropdownMenuItem>
                                <DropdownMenuItem
                                  onClick={() => {
                                    setDeletingReport(report);
                                    setIsDeleteDialogOpen(true);
                                  }}
                                >
                                  <Trash className="mr-2 h-4 w-4" />
                                  Delete
                                </DropdownMenuItem>
                              </DropdownMenuContent>
                            </DropdownMenu>
                          ) : col.format ? (
                            col.format(report[col.field])
                          ) : (
                            report[col.field]
                          )}
                        </TableCell>
                      ))}
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
            <div className="mt-4">
              <Pagination>
                <PaginationContent>
                  <PaginationItem>
                    <PaginationPrevious
                      onClick={
                        currentPage > 1
                          ? () => setCurrentPage((prev) => prev - 1)
                          : undefined
                      }
                      className={
                        currentPage === 1
                          ? "pointer-events-none opacity-50"
                          : ""
                      }
                    />
                  </PaginationItem>
                  {Array.from({
                    length: Math.ceil(reports.length / entriesPerPage),
                  }).map((_, i) => (
                    <PaginationItem key={i}>
                      <PaginationLink
                        onClick={() => setCurrentPage(i + 1)}
                        isActive={currentPage === i + 1}
                      >
                        {i + 1}
                      </PaginationLink>
                    </PaginationItem>
                  ))}
                  <PaginationItem>
                    <PaginationNext
                      onClick={
                        currentPage < Math.ceil(reports.length / entriesPerPage)
                          ? () => setCurrentPage((prev) => prev + 1)
                          : undefined
                      }
                      className={
                        currentPage >=
                        Math.ceil(reports.length / entriesPerPage)
                          ? "pointer-events-none opacity-50"
                          : ""
                      }
                    />
                  </PaginationItem>
                </PaginationContent>
              </Pagination>
            </div>
          </>
        )}

        {/* Delete Confirmation Dialog */}
        <Dialog open={isDeleteDialogOpen} onOpenChange={setIsDeleteDialogOpen}>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Confirm Deletion</DialogTitle>
              <DialogDescription>
                Are you sure you want to delete this report? This action cannot
                be undone.
              </DialogDescription>
            </DialogHeader>
            <DialogFooter>
              <Button
                variant="outline"
                onClick={() => setIsDeleteDialogOpen(false)}
              >
                Cancel
              </Button>
              <Button variant="destructive" onClick={handleDeleteReport}>
                Delete
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </div>
    </Layout>
  );
}
